spring.application.name=SpringValidationBean

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:teste
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
#dependencia para consultar comandos de banco, visualizar nivel aprendizado

#Versão Spring 4
#spring.web.error.include-binding-errors=always
#spring.web.error.include-message=always

#Versão spring 3
server.error.include-binding-errors=always
server.error.include-message=always
